### ISSUE TITLE
Weekly Scrum - March 5-12th

### ISSUE THREAD

**Issue by DwangDistracted** [mpfan/Mini-Shopify#12]
- what have I done this week? (with link(s) to the relevant GitHub Issue(s))
- what will I do next week? (with link(s) to the relevant GitHub Issue(s))
- what is holding me back? (if applicable)

**Comment by DwangDistracted** [comment]
Completed Issue #31 - Create Model Objects: implemented persistence for model objects.
Participated in Issue #23 - helped define and implement database schema
Participated in Planning and Scoping of Project.

WIP Issue #16

**Comment by Weebian** [comment]
Participated in Issue #23
WIP Issue #26

**Comment by Weebian** [comment]
Completed Issue #26

**Comment by mpfan** [comment]
Completed PR
- Configure Travis CI #7 
- Setup flyway migrator #27 
- Setup Vue for CI and local development #30 #34 
- Participated in making the database schema #28 
- Setting up Postgres on heroku #9 
- Product controller and views #37 #46 

Participated in Planning and Scoping of Project.

**Comment by Souheil-Yazji** [comment]
What have I done this week? (with link(s) to the relevant GitHub Issue(s))

Participated in Issue #4 - Helped with Travis Configuration and app deployment debugging
Completed Issue #5 - Created the heroku app, added api key for TravisCI
Partially completed Issue #25 - Added a fully functional header
Completed Issue #24 - Added a fully functional home view
Contributed to Issue #44 - updated routing of new components
Participated in Planning and Scoping of Project.

What will I do next week? (with link(s) to the relevant GitHub Issue(s))
Address Issue #15 - this involves creating login and signup pages, configuring authentication in the backend with Google OAuth, presisting user sessions, implementing access control. The issue may become more granulated later since it is large.
Address Issue #25  - maybe add a footer if time permits, not an essential component, could be dropped.

what is holding me back? (if applicable)
No blockers as of  yet.

**Comment by dershao** [comment]
What have I done this week? (with link(s) to the relevant GitHub Issue(s))

- Setting up project #6 
- Participated in Issue #23 for defining database schema
- Created view for Shop details #17
- Created controllers for Shop entity #36 
- Participated in Planning and Scoping of Project.

What will I do next week? (with link(s) to the relevant GitHub Issue(s))
- TBD

What is holding me back? (if applicable)
- None at the moment.
